# permissions for end users to edit kanikobuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kboperator
    app.kubernetes.io/managed-by: kustomize
  name: kanikobuild-editor-role
rules:
- apiGroups:
  - kbo.k8s.dav.io
  resources:
  - kanikobuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kbo.k8s.dav.io
  resources:
  - kanikobuilds/status
  verbs:
  - get
