---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - jobs
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kbo.k8s.dav.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kbo.k8s.dav.io
  resources:
  - kanikobuilds/finalizers
  verbs:
  - update
- apiGroups:
  - kbo.k8s.dav.io
  resources:
  - kanikobuilds/status
  verbs:
  - get
  - patch
  - update
